env:
 - GHCVER=6.12.3
 - GHCVER=7.0.1
 - GHCVER=7.0.2
 - GHCVER=7.0.3
 - GHCVER=7.0.4
 - GHCVER=7.2.1
 - GHCVER=7.2.2
 - GHCVER=7.4.1
 - GHCVER=7.4.2
 - GHCVER=7.6.1
 - GHCVER=7.6.2
 - GHCVER=7.6.3

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.18 ghc-$GHCVER

install:
 - cabal-1.18 update
 - PATH=/opt/ghc/$GHCVER/bin:$PATH cabal-1.18 install --only-dependencies
 - PATH=/opt/ghc/$GHCVER/bin:$PATH cabal-1.18 install 'QuickCheck==2.6.*'

script:
 - cd tests/ && PATH=/opt/ghc/$GHCVER/bin:$PATH runghc ./GenTests.hs && cd ..
 - ls -l tests/
 - PATH=/opt/ghc/$GHCVER/bin:$PATH cabal-1.18 configure --enable-tests -v2
 - cabal-1.18 build
 - cabal-1.18 test